export const buttonBankManagerLogin = `//button[contains(text(),'Bank Manager Login')]`;
export const buttonAddCustomerPage = `//button[contains(text(),'Add Customer')]`;
export const inputFirstName = `//input[@ng-model='fName']`;
export const inputLastName = `//input[@ng-model='lName']`;
export const inputPostalCode = `//input[@ng-model='postCd']`;
export const buttonAddCustomer = `//button[@type='submit' and contains(text(),'Add Customer')]`;
export const buttonAddOpenAccountPage = `//button[contains(text(),'Open Account')]`;
export const selectFieldCustomer = `//select[@id='userSelect']`;
export const selectFieldCurrency = `//select[@id='currency']`;
export const buttonAddOpenAccount = `//button[contains(text(),'Process')]`;
export const buttonCustomerPage = `//button[contains(text(),'Customers')]`;
export const inputSearchCustomer = `//input[@ng-model='searchCustomer']`;
export const customerFirstName = `//tbody//tr[1]//td[1]`;
